### ISSUE TITLE
Global speed

### ISSUE THREAD

**Issue by Gktwo** [Z4ee/StarRail-S-GC#1]
unityplayer.dll+1D21D78+FC

**Comment by camdao** [comment]
how to build dll . file

**Comment by Teruhashi12** [comment]
> unityplayer.dll+1D21D78+FC

like this??
![like this](https://user-images.githubusercontent.com/90950171/235359480-42aa08a1-b77e-4fde-8fca-af3d732724d7.PNG)

**Comment by Bartx92** [comment]
> unityplayer.dll+1D21D78+FC

"unityplayer.dll"+1D21D78+FC  ????
float?

**Comment by Z4ee** [comment]
[added in cheat](https://github.com/Z4ee/StarRail-S-GC/commit/f178bd120a08a44248b8f6229817a1fb381de42a)
