### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by knixnkk** [Z4ee/StarRail-S-GC#10]
need Damage increase or auto dialog, skip cutscene something like that. It's will so helpful!

**Comment by madeinhvn** [comment]
Looks tough rn as the game performs a sanity check. So even if you manage to modify the numbers using CE, it will throw an error once the match ends.

**Comment by Suntz246** [comment]
Part of the game data is verified and synchronized by the server, which is a complex issue and cannot be easily modified
