### ISSUE TITLE
dll

### ISSUE THREAD

**Issue by hAZEQUCIKIEE** [Z4ee/StarRail-S-GC#14]
hey can i get the new dll?

**Comment by Suntz246** [comment]
new dll:https://drive.google.com/file/d/1cAIQq-UfCb7OBFa7uyZ8v04G-qrWBMRC/view?usp=share_link

**Comment by Guilty** [comment]
> new dll:https://drive.google.com/file/d/1cAIQq-UfCb7OBFa7uyZ8v04G-qrWBMRC/view?usp=share_link

This seems to be the old one not new, the new one includes auto battle

**Comment by Suntz246** [comment]
> > new dll:https://drive.google.com/file/d/1cAIQq-UfCb7OBFa7uyZ8v04G-qrWBMRC/view?usp=share_link 新的 dll： https://drive.google.com/file/d/1cAIQq-UfCb7OBFa7uyZ8v04G-qrWBMRC/view?usp=share_link
> 
> This seems to be the old one not new, the new one includes auto battle这个好像是旧的不是新的，新的有自动战斗



> > new dll:https://drive.google.com/file/d/1cAIQq-UfCb7OBFa7uyZ8v04G-qrWBMRC/view?usp=share_link
> 
> This seems to be the old one not new, the new one includes auto battle

I have retrieved the warehouse and recompiled for testing, and the files have been updated

**Comment by roskiboy** [comment]
[Star-Rail-GC.zip](https://github.com/Z4ee/StarRail-S-GC/files/11394148/Star-Rail-GC.zip)
FIX FPS UNLOCK

**Comment by roskiboy** [comment]
> roskiboy can you teach me how to compile this in visual studio?

Just download visual studio, add the C options and that's it. You open the solution, select the solution > clear and rebuild and the dll would be ready
![image](https://user-images.githubusercontent.com/6926155/236126564-39eaa6cd-a8f0-47a3-8d62-a9051652a15d.png)
![image](https://user-images.githubusercontent.com/6926155/236126286-ee7538d7-0f2b-421f-83aa-853f39d32c43.png)
![image](https://user-images.githubusercontent.com/6926155/236126378-b6bf2aa1-ca48-4873-9708-c05e4b294a42.png)
![image](https://user-images.githubusercontent.com/6926155/236126461-dcdcc42e-0890-4617-b09f-108f06268fd3.png)

**Comment by Miraiiii** [comment]
can u help me run this hack?

**Comment by Suntz246** [comment]
> 

https://youtu.be/pIr6wQtz4kw

**Comment by Miraiiii** [comment]
What should i do? 
![image](https://user-images.githubusercontent.com/132566208/236181319-3f9d52fa-2c6f-47dc-97a5-fb4a19676055.png)

**Comment by Camiao64** [comment]
> > roskiboy can you teach me how to compile this in visual studio?
> 
> Just download visual studio, add the C options and that's it. You open the solution, select the solution > clear and rebuild and the dll would be ready ![image](https://user-images.githubusercontent.com/6926155/236126564-39eaa6cd-a8f0-47a3-8d62-a9051652a15d.png) ![image](https://user-images.githubusercontent.com/6926155/236126286-ee7538d7-0f2b-421f-83aa-853f39d32c43.png) ![image](https://user-images.githubusercontent.com/6926155/236126378-b6bf2aa1-ca48-4873-9708-c05e4b294a42.png) ![image](https://user-images.githubusercontent.com/6926155/236126461-dcdcc42e-0890-4617-b09f-108f06268fd3.png)

assuming this is visual studio 2019, ive installed all the C options but when attempting to build i get missing build tools v143

**Comment by SaoBap** [comment]
thnk you ill try later...

**Comment by Suntz246** [comment]
> > > roskiboy can you teach me how to compile this in visual studio?
> > 
> > 
> > Just download visual studio, add the C options and that's it. You open the solution, select the solution > clear and rebuild and the dll would be ready ![image](https://user-images.githubusercontent.com/6926155/236126564-39eaa6cd-a8f0-47a3-8d62-a9051652a15d.png) ![image](https://user-images.githubusercontent.com/6926155/236126286-ee7538d7-0f2b-421f-83aa-853f39d32c43.png) ![image](https://user-images.githubusercontent.com/6926155/236126378-b6bf2aa1-ca48-4873-9708-c05e4b294a42.png) ![image](https://user-images.githubusercontent.com/6926155/236126461-dcdcc42e-0890-4617-b09f-108f06268fd3.png)
> 
> assuming this is visual studio 2019, ive installed all the C options but when attempting to 
First download this project: https://github.com/TsudaKageyu/minhook,
Compile minhook lib:
Enter ..\minhook\build\VC17 to open the ending solution, right click to set the properties of the two solutions, set
![image](https://user-images.githubusercontent.com/49502214/236183874-21eaa918-4329-456a-a43a-754fec05fab3.png)
![image](https://user-images.githubusercontent.com/49502214/236183988-c5265428-2799-4f6a-8def-21802e6af8c4.png)
![image](https://user-images.githubusercontent.com/49502214/236184600-6cc4611a-d172-444c-93e9-4ca7a09324dd.png)
Rename libMinHook.x64.lib->minhook.lib under ..\minhook\build\VC17\lib\Release and replace it with StarRail-S-GC
public
Right-click on StarRail-S-GC to set the properties of the two solutions to be consistent with those of minhook, compile, and complete

**Comment by Camiao64** [comment]
> 

compiling minhook gives me a libminhook x86 file instead of x64 any idea what im doing wrong? (sorry kinda new to this)

**Comment by Suntz246** [comment]
> 

Have you set it this way?
![image](https://user-images.githubusercontent.com/49502214/236191625-ca3c89f8-3963-4960-b94e-969230d01351.png)

**Comment by Camiao64** [comment]
ah that fixed it thanks

**Comment by Miraiiii** [comment]
i cant run it :(

**Comment by Suntz246** [comment]
> i cant run it :(

Is it still not possible to turn off antivirus and follow the video tutorial?
**https://youtu.be/pIr6wQtz4kw**

**Comment by Suntz246** [comment]
> > > i cant run it :( 我无法运行它:(
> > 
> > 
> > Is it still not possible to turn off antivirus and follow the video tutorial? **https://youtu.be/pIr6wQtz4kw**还是不能关掉杀毒按照视频教程来做？ **https://youtu.be/pIr6wQtz4kw**
> 
> yea, i still cant run the hack是的，我仍然无法运行 hack
Is your operating system Windows 11?

**Comment by Miraiiii** [comment]
> > > > i cant run it :( 我无法运行它:(
> > > 
> > > 
> > > Is it still not possible to turn off antivirus and follow the video tutorial? **[https://youtu.be/pIr6wQtz4kw**还是不能关掉杀毒按照视频教程来做？](https://youtu.be/pIr6wQtz4kw**%E8%BF%98%E6%98%AF%E4%B8%8D%E8%83%BD%E5%85%B3%E6%8E%89%E6%9D%80%E6%AF%92%E6%8C%89%E7%85%A7%E8%A7%86%E9%A2%91%E6%95%99%E7%A8%8B%E6%9D%A5%E5%81%9A%EF%BC%9F) **https://youtu.be/pIr6wQtz4kw**
> > 
> > 
> > yea, i still cant run the hack是的，我仍然无法运行 hack
> > Is your operating system Windows 11?
yup

**Comment by Suntz246** [comment]
> > > > > i cant run it :( 我无法运行它:(
> > > > 
> > > > 
> > > > Is it still not possible to turn off antivirus and follow the video tutorial? **[https://youtu.be/pIr6wQtz4kw**还是不能关掉杀毒按照视频教程来做？](https://youtu.be/pIr6wQtz4kw**%E8%BF%98%E6%98%AF%E4%B8%8D%E8%83%BD%E5%85%B3%E6%8E%89%E6%9D%80%E6%AF%92%E6%8C%89%E7%85%A7%E8%A7%86%E9%A2%91%E6%95%99%E7%A8%8B%E6%9D%A5%E5%81%9A%EF%BC%9F) **https://youtu.be/pIr6wQtz4kw**
> > > 
> > > 
> > > yea, i still cant run the hack是的，我仍然无法运行 hack
> > > Is your operating system Windows 11?
> > > yup

Re edit your Issues, describe clearly your operating system environment and how you caused this consequence, and wait for further response from the author

**Comment by roskiboy** [comment]
GitActions for dll builds can be added automatically for each commit to the main/master branch.

**Comment by Z4ee** [comment]
> > > i cant run it :(
> > 
> > 
> > Is it still not possible to turn off antivirus and follow the video tutorial? **https://youtu.be/pIr6wQtz4kw**
> 
> yea, i still cant run the hack



> i cant run it


what do you mean by "i cant run it"

you can't inject or compile?

**Comment by roskiboy** [comment]
Update DLL

speedhack | hotkey: CAPSLOCK
peeking (: | hotkey: F5
fps unlock | hotkey: F6
auto battle unlock | hotkey: F7
speedhack | hotkey: F1
peeking (: | hotkey: F2
fps unlock | hotkey: F3
auto battle unlock | hotkey: F4
auto dialogue | hotkey: CAPSLOCK

[Star-Rail-GC.zip](https://github.com/Z4ee/StarRail-S-GC/files/11404072/Star-Rail-GC.zip)
