### ISSUE TITLE
how to run?

### ISSUE THREAD

**Issue by Miraiiii** [Z4ee/StarRail-S-GC#18]
can someone please help me how to run this hack?

**Comment by Extrimist09** [comment]
use extreme injector

**Comment by roskiboy** [comment]
You may follow the [video](https://youtu.be/pIr6wQtz4kw) created by the author.

There are two open Issues, where the information is shared

https://github.com/Z4ee/StarRail-S-GC/issues/11
https://github.com/Z4ee/StarRail-S-GC/issues/14
