### ISSUE TITLE
Speedhack gets back to normal speed after cutscenes or combat.

### ISSUE THREAD

**Issue by djdoolky76** [Z4ee/StarRail-S-GC#2]
After you fought to battle or triggered a cutscene, the speed hack disappeared.

Alternative solution: press caps lock once again if the dialogue or game speed is back to normal state.

Hopefully, a fix can make it stay active once it's activated.

**Comment by Z4ee** [comment]
[fixed](https://github.com/Z4ee/StarRail-S-GC/commit/f178bd120a08a44248b8f6229817a1fb381de42a)
