### ISSUE TITLE
Auto Dialogue 

### ISSUE THREAD

**Issue by Camiao64** [Z4ee/StarRail-S-GC#23]
@Z4ee the auto dialog only works for dialogs that doesnt have animations eg the npcs who stand still doesnt work on cutscenes like the main story line where the camera moves and focuses on different characters

**Comment by Z4ee** [comment]
fixed
now you need to hold `CapsLock `at the beginning of the dialogue and release it after it ends
(in the future it is necessary to make a normal implementation)

**Comment by Camiao64** [comment]
> fixed now you need to hold `CapsLock `at the beginning of the dialogue and release it after it ends

thanks for fixing it may i ask if its possible to change it back into a toggle? im currently using your cheat alongside another one and would be more convenient that way. if there is a file i can edit to turn it back into a toggle

**Comment by ky-ler** [comment]
> > fixed now you need to hold `CapsLock `at the beginning of the dialogue and release it after it ends
> 
> thanks for fixing it may i ask if its possible to change it back into a toggle? im currently using your cheat alongside another one and would be more convenient that way. if there is a file i can edit to turn it back into a toggle

Changed it to be a toggle here
#24

**Comment by Camiao64** [comment]
thank you!
