### ISSUE TITLE
Auto Dialog Glitches the game 

### ISSUE THREAD

**Issue by meet447** [Z4ee/StarRail-S-GC#25]
![image](https://user-images.githubusercontent.com/51074036/236478512-5d76dfb3-9e19-4f95-be47-b09a2e791fcf.png)

**Comment by gabrielsmecrow** [comment]
happened to me too

**Comment by Vovadid** [comment]
Since this update, the game freezes not only during dialogues but also during battles. For example, the War Echo near the Star Express on the starting location freezes when the speed hack is turned on with a value of 6.

**Comment by luanon404** [comment]
this error because your speed too fast

**Comment by Vovadid** [comment]
> This error is because the game missed the event, after the character speaks, there will be an animation of 3s, if it is too fast, the event of that event will be lost.

But before the appearance of dialogue skipping, such a problem did not arise.

**Comment by Z4ee** [comment]
fixed
