### ISSUE TITLE
Compiled dll

### ISSUE THREAD

**Issue by Strigger7** [Z4ee/StarRail-S-GC#26]
With the help of Github Action, you don't even need to compile it by yourself
Here's how it [works](https://github.com/Strigger7/StarRail-S-GC-Release/blob/main/.github/workflows/main.yml)
No more "sus" dll, this is clean, built directly from the source
https://nightly.link/Strigger7/StarRail-S-GC-Release/workflows/main/main/StarRail-GC-Release.zip

**Comment by Z4ee** [comment]
now you can download injector and dll from releases
