### ISSUE TITLE
System.Exception: The injection method used returned NULL

### ISSUE THREAD

**Issue by luanon404** [Z4ee/StarRail-S-GC#28]
![image](https://user-images.githubusercontent.com/71830807/236519287-3a85a2db-5298-4ff8-b862-e1215e18518b.png)

**Comment by luanon404** [comment]
fixed, use nvidia gpu instead of amd gpu

**Comment by luanon404** [comment]
checked, the cause of the problem is not the gpu

**Comment by Strigger7** [comment]
i'd recommend to use gh injector, extreme mostly fail at injecting

**Comment by luanon404** [comment]
do you have link?


> i'd recommend to use gh injector, extreme mostly fail at injecting

**Comment by erryle01** [comment]
open extreme injector then click launch in hsr then inject

**Comment by luanon404** [comment]
> open extreme injector then click launch in hsr then inject or auto inject

always fail bro

**Comment by luanon404** [comment]
gh injector works perfectly
![image](https://user-images.githubusercontent.com/71830807/236611924-e3fc1122-fbca-4352-8bdb-3cea1e4cc546.png)

**Comment by erryle01** [comment]
> > open extreme injector then click launch in hsr then inject or auto inject
> 
> always fail bro

put StarRail.exe

**Comment by erryle01** [comment]
![image](https://user-images.githubusercontent.com/116331799/236651613-98da8010-2760-459f-b34f-25fc6ba2fa84.png)
![image](https://user-images.githubusercontent.com/116331799/236651648-05223707-5285-4186-9af9-d1bb4c1fc16d.png)
