### ISSUE TITLE
Auto dialogue stuck

### ISSUE THREAD

**Issue by OrigFifty** [Z4ee/StarRail-S-GC#29]
Sometimes when I use the auto dialogue function, it bugs at a random time and then I can't use it at all, thus I am stuck in a dialogue and need to restart the whole game

**Comment by Z4ee** [comment]
I will fix this when I rewrite the cheat

**Comment by OrigFifty** [comment]
Thanks for the response. I closed this issue because there was a similiar issue already opened.
Really love this cheat, keep up the good work!

**Comment by Z4ee** [comment]
fixed
