### ISSUE TITLE
Chinese version does not work

### ISSUE THREAD

**Issue by Suntz246** [Z4ee/StarRail-S-GC#3]
Input speed on the console after injection, but it does not take effect during battles

**Comment by Suntz246** [comment]
GameAssembly.dll:https://drive.google.com/file/d/1ujRP4Mfq1rD7uv7PYpdodOSEgs8DTGNP/view?usp=share_link

StarRailBase.dll:https://drive.google.com/file/d/1zoFO700zN1hBhKKaiAZsodqKTrOKm__X/view?usp=share_link

**Comment by powerpuffaks** [comment]
![image](https://user-images.githubusercontent.com/122727212/235367972-8d9337c5-9cc9-4d25-90eb-0a24f829d3be.png)

**Comment by Suntz246** [comment]
> ![图像](https://user-images.githubusercontent.com/122727212/235367972-8d9337c5-9cc9-4d25-90eb-0a24f829d3be.png)

I'm sorry that the translation made me overlook this point
