### ISSUE TITLE
cant open the game with release version

### ISSUE THREAD

**Issue by gabrielsmecrow** [Z4ee/StarRail-S-GC#32]
I tried to open the game with ur release and the game freezes in the gray screen.
I compile the project and works fine, but when i try to run the game in ur release version freezes.

![image](https://user-images.githubusercontent.com/93964229/236633755-ded1ff3f-5981-4059-bf80-0d9f9ce000a2.png)

**Comment by Z4ee** [comment]
thanks for saying

I don't know why this is happening

**Comment by gabrielsmecrow** [comment]
np, i'm gonna use the compiled dll for now

**Comment by gabrielsmecrow** [comment]
yep, i tried inject the dll that i compiled now and cant press start too, if u want i can record a video and up in ytb for u see

**Comment by Z4ee** [comment]
did you close the menu? if so, try alt+tab twice

**Comment by gabrielsmecrow** [comment]
now it works, i have to put the game in window mode and don't press alt tab in loading of the game
