### ISSUE TITLE
one hit kill

### ISSUE THREAD

**Issue by Camiao64** [Z4ee/StarRail-S-GC#33]
hi would it be possible for you to look into this? 
https://github.com/aderfa/star_rail/blob/master/ImGui%20DirectX%2011%20Kiero%20Hook/ohk.cpp
one hit kill but his cheat cannot be compiled.
would be nice if you could add something like this ty

**Comment by Z4ee** [comment]
there will be an error 2002

![image](https://user-images.githubusercontent.com/113752393/236634305-fa5858cf-d4f9-4979-96e9-4f5ffb591b6c.png)
