### ISSUE TITLE
menu mod take game layout, cant interact

### ISSUE THREAD

**Issue by luanon404** [Z4ee/StarRail-S-GC#36]

**Comment by Z4ee** [comment]
idk but you can use any other injector

**Comment by luanon404** [comment]
still nothing happen, but if i inject dll file, i cant start game

**Comment by Z4ee** [comment]
https://github.com/Z4ee/StarRail-S-GC/issues/32

**Comment by luanon404** [comment]
> still nothing happen, but if i inject dll file, i cant start game

your menu take game layout, must hide menu if i want interact
