### ISSUE TITLE
auto dialog still error, game freeze

### ISSUE THREAD

**Issue by luanon404** [Z4ee/StarRail-S-GC#38]

**Comment by Z4ee** [comment]
can you be more specific, at what speed, when it happened

**Comment by luanon404** [comment]
> be more specific, at what speed, when it happened?

i will send u account do you have telegram or anything?

**Comment by luanon404** [comment]
wait, they added skip dialog button

**Comment by luanon404** [comment]
can u check for this 
![image](https://user-images.githubusercontent.com/71830807/236635733-2cccb744-d2d4-4c0e-a66c-8e6c314a7746.png)

**Comment by luanon404** [comment]
skip dialog button

**Comment by Z4ee** [comment]
I'll see what I can do about it tomorrow

**Comment by luanon404** [comment]
> I'll see what I can do about it tomorrow

do you need my account? i can send you, just give me way to contact with you😁
