### ISSUE TITLE
activating speed always makes verification failure (2010) in battle

### ISSUE THREAD

**Issue by dovalie** [Z4ee/StarRail-S-GC#39]
guess the speed code got broke (?) because anytime i speed up with global speed or battle speed, it causes the game to do a verification error (2010)

**Comment by AFKPika15** [comment]
Same, I also experienced something like this

**Comment by shaime666** [comment]
sameeeee

**Comment by jcg9081** [comment]
Unfortunately same error.. setting speed past 3.0 cause error 2010.  old version didn't have this issue.

**Comment by fatinghenji** [comment]
The same error was encountered. Other issues mention what appears to be a stacking situation between global speed and combat speed. Has anyone done any testing on this? Does adjusting only global speed or battle speed cause this problem?

**Comment by Z4ee** [comment]
fixed
