### ISSUE TITLE
cannot select the starail.exe file

### ISSUE THREAD

**Issue by Aditya990-jpg** [Z4ee/StarRail-S-GC#41]
starrail path path not found. Please point to it manually.Failed to create game process.If you have problem with StarRail.exe path. You can change it manually in cfg.ini.Failed to open GenshinImpact process.
Press any key to continue

**Comment by shaime666** [comment]
run the injector as administrator and it will work

**Comment by Aditya990-jpg** [comment]
> run the injector as administrator and it will work

hm i got thx
