### ISSUE TITLE
extremely lag when using speedhack

### ISSUE THREAD

**Issue by TuanAnh2901** [Z4ee/StarRail-S-GC#43]
When I turn on the injector and link into the game exe file, it doesn't work because the path error. You have to run with administrator to work correctly

**Comment by TuanAnh2901** [comment]
And the injector make the game use cpu really much ( especially with my potato laptop, the cpu usage increase 35% ). Using the dll only make less lag to the game.

**Comment by luanon404** [comment]
> Và bộ tiêm làm cho trò chơi sử dụng cpu rất nhiều (đặc biệt là với chiếc máy tính xách tay khoai tây của tôi, mức sử dụng cpu tăng 35%). Sử dụng dll chỉ làm giảm độ trễ cho trò chơi.

sài máy xịn đi

**Comment by luanon404** [comment]
> And the injector make the game use cpu really much ( especially with my potato laptop, the cpu usage increase 35% ). Using the dll only make less lag to the game.

sài máy xịn đi

**Comment by TuanAnh2901** [comment]
Ko phải là do máy cùi hay ko mà là cái speed của tool bị ngáo nên lúc thì ăn verification failed với load nhiều cpu vl ra. Speed bằng dll thuần không tăng cpu máy t lên hơn 90% 1 app như này đâu :))) nó vẫn chỉ giữ ở 50 - 70% th
