### ISSUE TITLE
laggy

### ISSUE THREAD

**Issue by gabrielsmecrow** [Z4ee/StarRail-S-GC#47]
can u share this version with the new features without the gui? in the pasts versions this cheat its awsome, but in this release its laggy af

**Comment by TuanAnh2901** [comment]
he updated the code, the new dll may less lag ( work with me ) and have config save. You can compile the new dll and replace the old dll

**Comment by Tearlament** [comment]
my game just straight up stops responding

**Comment by gabrielsmecrow** [comment]
new update fixed the lag for me, but i have to use extreme injector, if i launch in launcher of this cheat the game stops
