### ISSUE TITLE
An error 

### ISSUE THREAD

**Issue by Gktwo** [Z4ee/StarRail-S-GC#5]
![image](https://user-images.githubusercontent.com/52039418/235449395-12109901-306c-4832-b44e-52b532a70ee2.png)
During the battle, there was no change in battle speed, but rather global speed，get_currect_phase not work?（chinese server）

**Comment by Z4ee** [comment]
fixed

setcurrentphase in the Chinese version of the game - gameassembly.dll + 0x5B9DFD0
