### ISSUE TITLE
latest gui auto reset when interact

### ISSUE THREAD

**Issue by luanon404** [Z4ee/StarRail-S-GC#51]
example i changed speed 5, then ~ 3 secconds, that reset default, speed 1

**Comment by luanon404** [comment]
https://user-images.githubusercontent.com/71830807/236659847-24f11148-b8a6-46f3-9429-a7ec612bc0ec.mp4

**Comment by luanon404** [comment]
after reset, battle speed lower than before use speed hack

**Comment by ky-ler** [comment]
is this the version with a config file? let me look into it

**Comment by luanon404** [comment]
> is this the version with a config file? let me look into it

no, i build dll then inject to game not use v2 launcher

**Comment by ky-ler** [comment]
Okay I fixed it. Going to make a pull request give me a second

**Comment by luanon404** [comment]
> Okay I fixed it. Going to make a pull request give me a second

wait you are author, bro i found u

**Comment by ky-ler** [comment]
> > Okay I fixed it. Going to make a pull request give me a second
> 
> wait you are author, bro i found u

no I just like to contribute :)

**Comment by luanon404** [comment]
wait u are not author, sorry my mistake

**Comment by YinBuLiao** [comment]
![image](https://user-images.githubusercontent.com/35324248/236663326-f5b16f2b-b004-4b87-913a-ceb0a0d5f21d.png)
AUTO BATTLE will give a calibration error 2010

**Comment by luanon404** [comment]
> ![image](https://user-images.githubusercontent.com/35324248/236663326-f5b16f2b-b004-4b87-913a-ceb0a0d5f21d.png) AUTO BATTLE will give a calibration error 2010

i know your uid

**Comment by YinBuLiao** [comment]
> > AUTO BATTLE will give a calibration error 2010
> 
> i know your uid

I forgot to hide it, please delete the reply

**Comment by Z4ee** [comment]
all fixed

**Comment by luanon404** [comment]
> > > AUTO BATTLE will give a calibration error 2010
> > 
> > 
> > i know your uid
> 
> I forgot to hide it, please delete the reply, thx

😈 or 😇, choice one

**Comment by YinBuLiao** [comment]
> > > > AUTO BATTLE will give a calibration error 2010
> > > 
> > > 
> > > i know your uid
> > 
> > 
> > I forgot to hide it, please delete the reply, thx
> 
> 😈 or 😇, choice one

😇
