### ISSUE TITLE
Feature request (Add fps info)

### ISSUE THREAD

**Issue by djdoolky76** [Z4ee/StarRail-S-GC#53]
if possible, can you add fps info in Imgui

**Comment by Z4ee** [comment]
added

**Comment by djdoolky76** [comment]
can you also add fps info in a separate window like this? for monitoring purposes.

![image](https://user-images.githubusercontent.com/30578879/236682880-5cb6d81d-2f29-4c3c-a91f-c4d41288c57e.png)
