### ISSUE TITLE
can i interact without press F1 to hide menu mod?

### ISSUE THREAD

**Issue by luanon404** [Z4ee/StarRail-S-GC#54]

**Comment by Z4ee** [comment]
you cannot interact with the game without closing the menu

![image](https://user-images.githubusercontent.com/113752393/236664336-b17ed4bf-8966-464d-a6f4-abb2c261e54f.png)

**Comment by luanon404** [comment]
> you cannot interact with the game without closing the menu
> 
> ![image](https://user-images.githubusercontent.com/113752393/236664336-b17ed4bf-8966-464d-a6f4-abb2c261e54f.png)

so is the pid of the dll different from the pid of the game?

**Comment by Z4ee** [comment]
> > you cannot interact with the game without closing the menu
> > ![image](https://user-images.githubusercontent.com/113752393/236664336-b17ed4bf-8966-464d-a6f4-abb2c261e54f.png)
> 
> so is the pid of the dll different from the pid of the game?

?
