### ISSUE TITLE
Verification error (2010)  when changing battle speed

### ISSUE THREAD

**Issue by Architex-1024** [Z4ee/StarRail-S-GC#63]
then says Already in the battle

**Comment by Architex-1024** [comment]
The old one is fine

**Comment by Z4ee** [comment]
Can you make a video?

**Comment by luanon404** [comment]
note: Remember to hide your uid if you make a video

**Comment by Aditya990-jpg** [comment]
> then says Already in the battle

dude its not after the afternoon update

**Comment by Architex-1024** [comment]
@Aditya990-jpg ur right, it's ok now with the newest code
