### ISSUE TITLE
battle speed

### ISSUE THREAD

**Issue by GC-Ruth** [Z4ee/StarRail-S-GC#67]
![image](https://user-images.githubusercontent.com/107023226/236682507-c9ff8fac-354f-4948-9a65-ec2762b07b22.png)
I think it should be 2.f here, otherwise it looks like 0.5x even if the combat speed is not turned on

**Comment by Z4ee** [comment]
347 line? I have a total of 343 lines in Cheat.h

**Comment by GC-Ruth** [comment]
![image](https://user-images.githubusercontent.com/107023226/236683049-0fc152e2-e41b-423f-919f-8a6ebecaa7ec.png)
Sorry, because I thought the scroll bar was too difficult to control, I added manual input, resulting in a different code location

**Comment by Z4ee** [comment]
I don’t understand you very well, you sent me a code that restores the battle speed if you are in the world
Default battle speed is 1.0

**Comment by GC-Ruth** [comment]
Because I don't think anyone will use 1.0 speed, it's better to default to 2.0

**Comment by Z4ee** [comment]
the player animation will glitch in the world

that's why I use global speed in the world and battle speed in battle
