### ISSUE TITLE
Not work in Chinese version

### ISSUE THREAD

**Issue by nosilence1994** [Z4ee/StarRail-S-GC#8]
This is the version of StarRail.
![image](https://user-images.githubusercontent.com/13042974/235570200-aa8c5eec-7de7-494e-9f71-2a8fb90848df.png)

This is my config of Extreme Injector.
![image](https://user-images.githubusercontent.com/13042974/235570460-6141fe8a-98ef-4e01-9ea3-ea36f9dbf422.png)

When I launch StarRail.exe directly, it seems inject success.
![image](https://user-images.githubusercontent.com/13042974/235570261-9e81458b-4d96-4ef0-a127-225369566a18.png)

However, when I press CAPSLOCK, I just only hear one voice from speakers, but nothing print in console and nothing happens to the game.

When I press F6, I hear one voice and the game screen becomes not fluently as before, when I press F6 again,   it recovers.

**Comment by Z4ee** [comment]
maybe you don't set the speedhack speed
u need change current speed value by writing desired speed to console

**Comment by nosilence1994** [comment]
Yout are right, it worked.
![image](https://user-images.githubusercontent.com/13042974/235574545-f9071cdc-7bd3-4ba5-897c-38398539dbce.png)

**Comment by nosilence1994** [comment]
By the way, what is PEEKING used for?

**Comment by Z4ee** [comment]
https://github.com/Z4ee/StarRail-S-GC/issues/6
