### ISSUE TITLE
chinese version dosen‘t work

### ISSUE THREAD

**Issue by NTnarasha** [Z4ee/StarRail-S-GC#9]
![image](https://user-images.githubusercontent.com/58031155/235572086-34b17784-8641-48ac-8b4c-c2d2832012f7.png)
game version 
![image](https://user-images.githubusercontent.com/58031155/235572149-c7b54bc8-b794-4e86-9050-25db4623033e.png)

**Comment by Z4ee** [comment]
https://youtu.be/pIr6wQtz4kw

**Comment by NTnarasha** [comment]
thanks i have done this follow the video Огромное спасибо
